# These are supported funding model platforms

github: centralmacatuba # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: centralmacatuba # Replace with a single Patreon username
open_collective: centralmacatuba # Replace with a single Open Collective username
ko_fi: centralmacatuba # Replace with a single Ko-fi username
tidelift: centralmacatuba # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: centralmacatuba # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: centralmacatuba # Replace with a single Liberapay username
issuehunt: centralmacatuba # Replace with a single IssueHunt username
lfx_crowdfunding: centralmacatuba # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: centralmacatuba # Replace with a single Polar username
buy_me_a_coffee: centralmacatuba # Replace with a single Buy Me a Coffee username
thanks_dev: centralmacatuba # Replace with a single thanks.dev username
custom: https://macatuba.eliasempresas.com/doar # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
